export const input1 = `
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam faucibus consequat tortor ut dictum. Mauris orci mi, porta a leo eu, molestie tristique augue. Sed tempor ornare nisi, eget finibus nisi ullamcorper ut. Quisque at odio est. Ut viverra lacinia erat, ut vestibulum purus iaculis consequat. Suspendisse sed faucibus leo. Praesent turpis nisl, porta sed fringilla at, hendrerit vel justo. Donec pellentesque ullamcorper mi, sed eleifend nisi rutrum et. Sed ut rhoncus lorem. Cras velit nulla, congue in tempus ut, tempus vel mi. In hac habitasse platea dictumst. Maecenas nec enim dapibus, mollis ipsum non, eleifend nisl.

  Integer at luctus enim. Fusce mattis luctus tortor, non aliquet enim imperdiet in. Nullam et tristique nunc. Praesent vitae finibus ipsum. Aliquam aliquam non augue at consectetur. Aliquam id rutrum ex. Duis eget risus id arcu egestas scelerisque eget quis justo. Nam rhoncus volutpat purus non placerat. Mauris ut enim magna. Phasellus faucibus accumsan pretium. Duis congue massa sit amet tempor rhoncus.

  Sed tincidunt elit eu nibh tempor consequat. Nunc vel nunc at number 1234567891011 orci placerat imperdiet. Nullam maximus purus quis turpis dictum pellentesque. In et tellus tincidunt, gravida erat non, fermentum odio. Aliquam id purus massa. Proin nec tortor eu turpis cursus hendrerit ac quis lacus. Integer vel augue lorem. Donec laoreet ante id facilisis consectetur. Aenean consequat dui massa, ac viverra urna vehicula et. Phasellus maximus orci et libero commodo elementum. Vestibulum quam orci, interdum sit amet massa mattis, pulvinar euismod lorem. Sed ac elit sollicitudin, cursus arcu eu, aliquam ligula.

  Nulla egestas consequat nunc, a sodales augue rhoncus at. Sed nulla tortor, tristique et sem eget, sodales hendrerit massa. Nulla nec arcu eu metus porta sagittis at et odio. Duis vel tellus posuere, bibendum eros ac, eleifend elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis pharetra purus non orci vehicula fermentum. Suspendisse potenti. Sed consequat velit congue efficitur tincidunt. Suspendisse ut elementum sapien. Proin congue ut magna in condimentum.

  Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur ornare mollis sagittis. Aenean varius ante at velit vestibulum, ut consectetur ipsum consequat. Mauris tincidunt sodales accumsan. Sed facilisis sollicitudin odio in molestie. Praesent congue, odio in dictum laoreet, tortor metus cursus diam, quis tristique arcu dui in felis. Donec pulvinar est laoreet, condimentum leo ac, interdum sapien. Proin et sem bibendum, pulvinar erat non, feugiat justo. Integer congue bibendum aliquet. Donec faucibus at velit sed vestibulum. Donec urna tellus, luctus quis fermentum sed, suscipit eu turpis. Quisque eget lacinia ipsum. Quisque iaculis, justo nec fermentum vestibulum, mi ante porttitor ante, et eleifend augue urna non arcu. Sed ullamcorper pellentesque pulvinar. Praesent tristique luctus massa, ac eleifend felis malesuada auctor. Sed aliquet vitae augue at imperdiet.
`;

export const input2 = `
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur placerat consequat lacus, sed ornare nulla tincidunt eget. Phasellus lacinia non sapien a luctus. Fusce in cursus lacus, eget convallis nunc. Etiam commodo viverra lectus sit amet hendrerit. Praesent ornare odio id nisi commodo, in cursus nisl hendrerit. Nunc vel massa eros. Nulla tempor pellentesque tellus quis varius. Quisque ut neque vel sapien maximus vestibulum. Nulla ut malesuada sem, nec porttitor urna. Suspendisse quam turpis, interdum nec lorem ut, suscipit ultrices nibh. Etiam cursus pellentesque cursus. Phasellus in fringilla sapien. Nunc ut pulvinar dolor. Aliquam erat volutpat.

  Cras dignissim, purus non venenatis scelerisque, lorem sapien commodo odio, a varius tellus dolor ut ante. Aliquam egestas ornare felis, quis pretium erat. Maecenas efficitur enim sem, nec fringilla justo aliquam vel. Vestibulum mollis ex a ipsum euismod, quis ultricies lectus volutpat. Donec dignissim ex in augue sodales, non volutpat dui lobortis. Quisque vulputate dapibus orci a semper. In ut sodales purus. Morbi ut cursus libero. Duis et quam at ligula bibendum scelerisque in eu massa.

  Vestibulum et libero iaculis, elementum velit non, auctor tellus. Nam dictum ligula et sodales elementum. Praesent mi ipsum, maximus a egestas faucibus, aliquam vitae ipsum. Curabitur ornare fermentum diam, quis ornare lacus mattis nec. Quisque sit amet aliquam tellus. Proin semper eget augue sit amet viverra. Phasellus placerat vitae turpis non commodo. Ut nisi nulla, rutrum sed dignissim ac, aliquam efficitur nisl. Fusce id venenatis elit. Sed eget augue leo. Sed ut erat orci. Sed nisl nunc, rhoncus in orci maximus, suscipit tristique nulla.

  Donec rhoncus nisi eget risus lacinia gravida ac at nibh. Cras ipsum lacus, congue ut leo sit amet, dictum blandit nulla. Ut leo ex, elementum ac elit ut, aliquet egestas metus. Cras ut orci sed ante egestas semper at nec diam. Proin ac vestibulum enim. Suspendisse potenti. Proin et auctor magna, mattis euismod erat. Fusce ornare odio vel facilisis eleifend. Nullam vitae congue nibh. Aliquam vitae dui nisl. Sed purus turpis, volutpat ut convallis sed, pulvinar sit amet mauris. Fusce risus est, lacinia maximus massa eget, maximus vestibulum lorem. Maecenas aliquam fermentum libero, id commodo diam lobortis eget. Donec id varius sem. Integer posuere non risus at finibus.

  Integer vehicula eget lacus quis luctus. Aliquam et accumsan magna. Phasellus in fermentum sem. Suspendisse sed libero quis nibh ornare blandit quis vel purus. Cras feugiat, augue eget pretium eleifend, quam nisi pharetra tortor, eu felis quam in tortor. Vestibulum id tincidunt magna. Sed in mauris egestas, gravida nisl nec, interdum urna. In ut euismod elit. In in luctus nisi, gravida ultrices ex. Nulla egestas, massa nec pellentesque pharetra, ligula ipsum tristique turpis, consectetur fermentum quam ante vel libero.
`;

export const input3 = `This is an example sentence. For dramatic effect here is another sentence.`;
